stages:          # List of stages for jobs, and their order of execution
  - type-check
  - tests
  - lint

type-check-job:       # This job runs in the build stage, which runs first.
  stage: type-check
  image: python:3.9
  before_script: 
    - pip install mypy types-attr types-requests
  script:
    - mypy zenora

run-tests:
  stage: tests
  image: python:3.9
  before_script:
    - pip install -r requirements.txt
    - pip install pytest
  script:
    - pytest

run-linting:
  stage: lint
  image: python:3.9
  before_script:
    - pip install flake8
  script:
    - flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    - flake8 . --count --exit-zero --statistics
